-- ═══════════════════════════════════════════════════════════════════
-- data/schema.sql
-- SQLite schema for Supply Demand Agentic AI
--
-- Tables:
--   1. skus                — product master
--   2. suppliers           — vendor master
--   3. sku_suppliers       — SKU ↔ Supplier mapping (many-to-many)
--   4. inventory_levels    — current on-hand stock per SKU per location
--   5. stock_movements     — every inbound/outbound transaction
--   6. orders              — customer demand history (daily aggregated)
--   7. purchase_orders     — POs generated by the Procurement Agent
--   8. purchase_order_lines— PO line items
--   9. workflow_runs       — every agentic workflow execution
--  10. agent_results       — per-agent results within a run
--  11. exception_events    — supply chain disruptions & alerts
-- ═══════════════════════════════════════════════════════════════════

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;   -- better concurrent read performance


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. skus — Product Master
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skus (
    sku_id              TEXT        PRIMARY KEY,
    name                TEXT        NOT NULL,
    category            TEXT        NOT NULL,
    unit_of_measure     TEXT        NOT NULL DEFAULT 'EA',
    unit_cost           REAL        NOT NULL CHECK (unit_cost > 0),
    unit_price          REAL        NOT NULL CHECK (unit_price > 0),
    weight_kg           REAL,
    storage_type        TEXT        NOT NULL DEFAULT 'ambient'
                                    CHECK (storage_type IN ('ambient','refrigerated','frozen','hazmat')),
    shelf_life_days     INTEGER,
    status              TEXT        NOT NULL DEFAULT 'active'
                                    CHECK (status IN ('active','discontinued','seasonal','new')),
    created_at          TEXT        NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_skus_category ON skus (category);
CREATE INDEX IF NOT EXISTS idx_skus_status   ON skus (status);


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. suppliers — Vendor Master
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id         TEXT        PRIMARY KEY,
    name                TEXT        NOT NULL,
    country             TEXT        NOT NULL,
    lead_time_days      INTEGER     NOT NULL CHECK (lead_time_days >= 0),
    min_order_qty       REAL        NOT NULL DEFAULT 0 CHECK (min_order_qty >= 0),
    unit_cost           REAL        NOT NULL CHECK (unit_cost > 0),
    reliability_score   REAL        NOT NULL DEFAULT 1.0
                                    CHECK (reliability_score BETWEEN 0 AND 1),
    status              TEXT        NOT NULL DEFAULT 'active'
                                    CHECK (status IN ('active','on_hold','preferred','blacklisted')),
    contact_email       TEXT,
    created_at          TEXT        NOT NULL DEFAULT (datetime('now'))
);


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. sku_suppliers — SKU ↔ Supplier Mapping
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sku_suppliers (
    sku_id          TEXT    NOT NULL REFERENCES skus(sku_id)           ON DELETE CASCADE,
    supplier_id     TEXT    NOT NULL REFERENCES suppliers(supplier_id) ON DELETE CASCADE,
    is_primary      INTEGER NOT NULL DEFAULT 0,  -- 1 = preferred supplier for this SKU
    contracted_cost REAL,                         -- override supplier.unit_cost if negotiated
    PRIMARY KEY (sku_id, supplier_id)
);


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. inventory_levels — Current On-Hand Stock Snapshot
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inventory_levels (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    sku_id          TEXT    NOT NULL REFERENCES skus(sku_id) ON DELETE CASCADE,
    location_id     TEXT    NOT NULL DEFAULT 'DC-01',
    on_hand         REAL    NOT NULL CHECK (on_hand >= 0),
    reserved        REAL    NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    in_transit      REAL    NOT NULL DEFAULT 0 CHECK (in_transit >= 0),
    reorder_point   REAL,
    safety_stock    REAL,
    eoq             REAL,
    last_updated    TEXT    NOT NULL DEFAULT (datetime('now')),
    expiry_date     TEXT,
    UNIQUE (sku_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_sku      ON inventory_levels (sku_id);
CREATE INDEX IF NOT EXISTS idx_inventory_location ON inventory_levels (location_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. stock_movements — Inventory Transaction Ledger
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_movements (
    movement_id     TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    sku_id          TEXT    NOT NULL REFERENCES skus(sku_id) ON DELETE CASCADE,
    location_id     TEXT    NOT NULL DEFAULT 'DC-01',
    movement_type   TEXT    NOT NULL
                            CHECK (movement_type IN (
                                'receipt','sale','adjustment',
                                'transfer_in','transfer_out','return','write_off'
                            )),
    quantity        REAL    NOT NULL CHECK (quantity > 0),  -- always positive; sign inferred from type
    reference_doc   TEXT,   -- PO number, SO number, or adjustment ref
    notes           TEXT,
    recorded_by     TEXT    NOT NULL DEFAULT 'inventory_agent',
    occurred_at     TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_movements_sku  ON stock_movements (sku_id);
CREATE INDEX IF NOT EXISTS idx_movements_date ON stock_movements (occurred_at);
CREATE INDEX IF NOT EXISTS idx_movements_type ON stock_movements (movement_type);


-- ─────────────────────────────────────────────────────────────────────────────
-- 6. orders — Customer Demand History (daily aggregated)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    order_date      TEXT    NOT NULL,   -- YYYY-MM-DD
    sku_id          TEXT    NOT NULL REFERENCES skus(sku_id) ON DELETE CASCADE,
    quantity        REAL    NOT NULL CHECK (quantity >= 0),
    channel         TEXT    NOT NULL DEFAULT 'default',  -- online, retail, wholesale
    region          TEXT,
    unit_price      REAL,
    UNIQUE (order_date, sku_id, channel)
);

CREATE INDEX IF NOT EXISTS idx_orders_sku  ON orders (sku_id);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders (order_date);


-- ─────────────────────────────────────────────────────────────────────────────
-- 7. purchase_orders — POs Generated by Procurement Agent
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_orders (
    po_number       TEXT    PRIMARY KEY,
    supplier_id     TEXT    NOT NULL REFERENCES suppliers(supplier_id),
    status          TEXT    NOT NULL DEFAULT 'draft'
                            CHECK (status IN ('draft','submitted','confirmed',
                                              'shipped','received','cancelled')),
    total_value     REAL,
    issued_date     TEXT    NOT NULL DEFAULT (date('now')),
    expected_date   TEXT,
    notes           TEXT,
    created_by_agent TEXT   NOT NULL DEFAULT 'procurement_agent',
    approved_by     TEXT,
    approved_at     TEXT,
    run_id          TEXT,   -- FK to workflow_runs (soft reference)
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders (supplier_id);
CREATE INDEX IF NOT EXISTS idx_po_status   ON purchase_orders (status);


-- ─────────────────────────────────────────────────────────────────────────────
-- 8. purchase_order_lines — PO Line Items
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    po_number   TEXT    NOT NULL REFERENCES purchase_orders(po_number) ON DELETE CASCADE,
    line_number INTEGER NOT NULL CHECK (line_number >= 1),
    sku_id      TEXT    NOT NULL REFERENCES skus(sku_id),
    description TEXT    NOT NULL DEFAULT '',
    quantity    REAL    NOT NULL CHECK (quantity > 0),
    unit_cost   REAL    NOT NULL CHECK (unit_cost > 0),
    line_total  REAL,   -- computed on insert: round(quantity * unit_cost, 2)
    UNIQUE (po_number, line_number)
);


-- ─────────────────────────────────────────────────────────────────────────────
-- 9. workflow_runs — Agentic Workflow Execution Records
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS workflow_runs (
    run_id          TEXT    PRIMARY KEY,
    status          TEXT    NOT NULL DEFAULT 'initialised'
                            CHECK (status IN ('initialised','running','paused',
                                              'completed','failed','cancelled')),
    sku_ids         TEXT    NOT NULL,  -- JSON array string e.g. '["SKU-001","SKU-002"]'
    triggered_by    TEXT    NOT NULL DEFAULT 'api',
    total_tokens    INTEGER DEFAULT 0,
    duration_secs   REAL,
    summary         TEXT,              -- JSON blob
    started_at      TEXT,
    completed_at    TEXT,
    created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_runs_status ON workflow_runs (status);
CREATE INDEX IF NOT EXISTS idx_runs_date   ON workflow_runs (created_at);


-- ─────────────────────────────────────────────────────────────────────────────
-- 10. agent_results — Per-Agent Output Within a Run
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS agent_results (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id          TEXT    NOT NULL REFERENCES workflow_runs(run_id) ON DELETE CASCADE,
    agent           TEXT    NOT NULL,
    status          TEXT    NOT NULL,
    output          TEXT,              -- JSON blob of agent-specific result
    error           TEXT,
    tokens_used     INTEGER,
    duration_secs   REAL,
    started_at      TEXT,
    completed_at    TEXT
);

CREATE INDEX IF NOT EXISTS idx_agent_results_run ON agent_results (run_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- 11. exception_events — Supply Chain Disruptions & Alerts
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS exception_events (
    event_id        TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    run_id          TEXT    NOT NULL REFERENCES workflow_runs(run_id) ON DELETE CASCADE,
    raised_by       TEXT    NOT NULL,
    exception_type  TEXT    NOT NULL,
    severity        TEXT    NOT NULL CHECK (severity IN ('info','warning','high','critical')),
    sku_id          TEXT,
    supplier_id     TEXT,
    description     TEXT    NOT NULL,
    context         TEXT,              -- JSON blob
    resolved        INTEGER NOT NULL DEFAULT 0,
    resolution      TEXT,
    raised_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    resolved_at     TEXT
);

CREATE INDEX IF NOT EXISTS idx_exceptions_run      ON exception_events (run_id);
CREATE INDEX IF NOT EXISTS idx_exceptions_severity ON exception_events (severity);
CREATE INDEX IF NOT EXISTS idx_exceptions_resolved ON exception_events (resolved);
